version: '3'

services:
  weshare-green-server1:
    container_name: weshare-green-1
    image: goodchoi/weshare
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8083

  weshare-green-server2:
    container_name: weshare-green-2
    image: goodchoi/weshare
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8084
