spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    #    properties:
    #      hibernate:
    #        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:/sql/init.sql
      mode: always

  data:
    redis:
      host: localhost
      port: 6370
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

async:
  threadNamePrefix: 'async-thread-'
  corePoolSize: 20
  maxPoolSize: 40
  queueCapacity: 400
  keepAliveSeconds: 30

