spring:
  config:
    import: optional:file:.env[.properties]

  batch:
    job:
      name: ${job.name:NONE}
      enabled: false

    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER_NAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          auth: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

pay:
  rest_application_id: ${REST_APPLICATION_ID}
  private_key: ${PRIVATE_KEY}

aes:
  password: ${AES_PASSWORD}
  salt: ${AES_SALT}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USER_NAME}
  password: ${GMAIL_PASSWORD}

batch:
  pay:
    chunksize: ${BATCH_PAY_CHUNKSIZE}
    savepath: ${BATCH_PAY_SAVEPATH}
    cachesize: ${BATCH_PAY_CACHESIZE}
