bootJar {
    enabled = true
}
jar {
    enabled = true
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}


task('buildAndRun2') {
    dependsOn 'build'
    finalizedBy 'dockerUpMAIL'
}

task('quickBuildUpMail') {
    dependsOn('assemble')
    finalizedBy('dockerUpMAIL')
}

task('dockerUpMAIL') {
    doLast {
        exec {
            commandLine 'docker-compose', 'up', '-d', '--build'
        }
    }
}
