bootJar {
    enabled = false
}
jar {
    enabled = true
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2' // Java 8 날짜/시간 지원
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.2'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

}
