spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          auth: false

jwt:
  access_expiration_time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh_expiration_time: ${JWT_REFRESH_EXPIRATION_TIME}
  secret: ${JWT_SECRET}

pay:
  rest_application_id: ${REST_APPLICATION_ID}
  private_key: ${PRIVATE_KEY}

aes:
  password: ${AES_PASSWORD}
  salt: ${AES_SALT}

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
