spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:/sql/init.sql
      mode: never

  data:
    redis:
      host: weshare_redis
      port: 6379

  rabbitmq:
    host: weshare_rabbitmq
    port: 5672
    username: weshare
    password: 1234

